struct Language: Identifiable, Hashable, Codable {
    let id: String // ISO kod
    let name: String // Türkçe ad
    let nameEn: String // English ad
}

struct LanguageListWrapper: Codable {
    let languages: [Language]
}
let supportedLanguages: [Language] = [
    
    Language(id: "", name: "Dili Algıla", nameEn: "Detect Language"),
    Language(id: "af", name: "Afrikanca", nameEn: "Afrikaans"),
    Language(id: "de", name: "Almanca", nameEn: "German"),
    Language(id: "sq", name: "Arnavutça", nameEn: "Albanian"),
    Language(id: "ar", name: "Arapça", nameEn: "Arabic"),
    Language(id: "dsb", name: "Aşağı Sorbça", nameEn: "Lower Sorbian"),
    Language(id: "eu", name: "Baskça", nameEn: "Basque"),
    Language(id: "ba", name: "Başkırtça", nameEn: "Bashkir"),
    Language(id: "be", name: "Belarusça", nameEn: "Belarusian"),
    Language(id: "bn", name: "Bangla", nameEn: "Bangla"),
    Language(id: "bho", name: "Bhojpuri", nameEn: "Bhojpuri"),
    Language(id: "my", name: "Myanmar", nameEn: "Burmese"),
    Language(id: "brx", name: "Bodo", nameEn: "Bodo"),
    Language(id: "bs", name: "Boşnakça (Latin)", nameEn: "Bosnian (Latin)"),
    Language(id: "bg", name: "Bulgarca", nameEn: "Bulgarian"),
    Language(id: "hne", name: "Çatisgarhi", nameEn: "Chhattisgarhi"),
    Language(id: "lzh", name: "Çince (Edebi)", nameEn: "Chinese (Literary)"),
    Language(id: "da", name: "Danca", nameEn: "Danish"),
    Language(id: "prs", name: "Dari lehçesi", nameEn: "Dari"),
    Language(id: "dv", name: "Divehi Dili", nameEn: "Divehi"),
    Language(id: "doi", name: "Dogri", nameEn: "Dogri"),
    Language(id: "id", name: "Endonezce", nameEn: "Indonesian"),
    Language(id: "hy", name: "Ermenice", nameEn: "Armenian"),
    Language(id: "et", name: "Estonya Dili", nameEn: "Estonian"),
    Language(id: "fo", name: "Faroe Dili", nameEn: "Faroese"),
    Language(id: "fa", name: "Farsça", nameEn: "Persian"),
    Language(id: "nl", name: "Felemenkçe", nameEn: "Dutch"),
    Language(id: "fi", name: "Fince", nameEn: "Finnish"),
    Language(id: "fr", name: "Fransızca", nameEn: "French"),
    Language(id: "fr-ca", name: "Fransızca (Kanada)", nameEn: "French (Canada)"),
    Language(id: "cy", name: "Galce", nameEn: "Welsh"),
    Language(id: "gl", name: "Galiçya Dili", nameEn: "Galician"),
    Language(id: "lug", name: "Ganda", nameEn: "Luganda"),
    Language(id: "el", name: "Yunanca", nameEn: "Greek"),
    Language(id: "zh-Hans", name: "Çince(Basitleştirilmiş)", nameEn: "Chinese (Simplified)"),
    Language(id: "zh-Hant", name: "Çince (Geleneksel)", nameEn: "Chinese (Traditional)"),
    Language(id: "gu", name: "Gucerat Dili", nameEn: "Gujarati"),
    Language(id: "ka", name: "Gürcüce", nameEn: "Georgian"),
    Language(id: "ht", name: "Haiti Kreyolu", nameEn: "Haitian Creole"),
    Language(id: "ha", name: "Hausa", nameEn: "Hausa"),
    Language(id: "hi", name: "Hintçe", nameEn: "Hindi"),
    Language(id: "hr", name: "Hırvatça", nameEn: "Croatian"),
    Language(id: "mww", name: "Hmong Daw (Latin)", nameEn: "Hmong Daw (Latin)"),
    Language(id: "ig", name: "Igbo", nameEn: "Igbo"),
    Language(id: "he", name: "İbranice", nameEn: "Hebrew"),
    Language(id: "is", name: "İzlandaca", nameEn: "Icelandic"),
    Language(id: "en", name: "İngilizce", nameEn: "English"),
    Language(id: "ikt", name: "İnuikçe", nameEn: "Inuit"),
    Language(id: "iu-Latn", name: "İnuitçe (Latin)", nameEn: "Inuktitut (Latin)"),
    Language(id: "iu", name: "Inuktitut Dili", nameEn: "Inuktitut"),
    Language(id: "ga", name: "Irlandaca", nameEn: "Irish"),
    Language(id: "es", name: "Ispanyolca", nameEn: "Spanish"),
    Language(id: "sv", name: "İsveççe", nameEn: "Swedish"),
    Language(id: "it", name: "Italyanca", nameEn: "Italian"),
    Language(id: "ja", name: "Japonca", nameEn: "Japanese"),
    Language(id: "yue", name: "Kantonca (Geleneksel)", nameEn: "Cantonese"),
    Language(id: "ks", name: "Kashmiri", nameEn: "Kashmir"),
    Language(id: "ca", name: "Katalanca", nameEn: "Catalan"),
    Language(id: "kk", name: "Kazakça", nameEn: "Kazakh"),
    Language(id: "rw", name: "Kinyarwanda", nameEn: "Kinyarwanda"),
    Language(id: "ky", name: "Kırgızca", nameEn: "Kyrgyz"),
    Language(id: "tlh-Latn", name: "Klingon", nameEn: "Klingon"),
    Language(id: "tlh-Piqd", name: "Klingonea (plqaD)", nameEn: "Klingon (plqaD)"),
    Language(id: "gom", name: "Konkani", nameEn: "Konkani"),
    Language(id: "ko", name: "Korece", nameEn: "Korean"),
    Language(id: "kmr", name: "Kurtce (Kuzey)", nameEn: "Kurdish (Northern)"),
    Language(id: "ku", name: "Kurtce (Orta)", nameEn: "Kurdish (Middle)"),
    Language(id: "lo", name: "Lao Dili", nameEn: "Lao"),
    Language(id: "lb", name: "Lüksemburgca", nameEn: "Luxembourgish"),
    Language(id: "pl", name: "Lehçe", nameEn: "Polish"),
    Language(id: "lv", name: "Letonca", nameEn: "Latvian"),
    Language(id: "ln", name: "Lingalaca", nameEn: "Lingala"),
    Language(id: "lt", name: "Litvanca", nameEn: "Lithuanian"),
    Language(id: "hu", name: "Macarca", nameEn: "Hungarian"),
    Language(id: "mai", name: "Maith", nameEn: "Maith"),
    Language(id: "mk", name: "Makedonca", nameEn: "Macedonian"),
    Language(id: "ml", name: "Malayalam Dili", nameEn: "Malayalam"),
    Language(id: "ms", name: "Malayca", nameEn: "Malay"),
    Language(id: "mg", name: "Malgaşca", nameEn: "Malagasy"),
    Language(id: "mt", name: "Maltaca", nameEn: "Maltese"),
    Language(id: "mni", name: "Manipuri", nameEn: "Manipur"),
    Language(id: "mr", name: "Marathi Dili", nameEn: "Marathi"),
    Language(id: "mn-Cyrl", name: "Moğolca (Kiril)", nameEn: "Mongolian (Cyrillic)"),
    Language(id: "mn-Mong", name: "Moğolca (Geleneksel)", nameEn: "Mongolian (Traditiona)"),
    Language(id: "ne", name: "Nepalce", nameEn: "Nepali"),
    Language(id: "nb", name: "Norvegce Bokmal", nameEn: "Norwegian Bokmål"),
    Language(id: "nya", name: "Çevaca", nameEn: "Nyanja"),
    Language(id: "or", name: "Oriya Dili", nameEn: "Odia"),
    Language(id: "uz", name: "Özbekçe", nameEn: "Uzbek"),
    Language(id: "pa", name: "Pencapça", nameEn: "Punjabi"),
    Language(id: "ps", name: "Peştuca", nameEn: "Pashto"),
    Language(id: "pt", name: "Portekizce (Brezilya)", nameEn: "Portuguese (Brazil)"),
    Language(id: "pt-pt", name: "Portekizce (Portekiz)", nameEn: "Portuguese (Portugal)"),
    Language(id: "otq", name: "Querétaro Otomi", nameEn: "Otomi"),
    Language(id: "ro", name: "Rumence", nameEn: "Romanian"),
    Language(id: "run", name: "Rundi", nameEn: "Kirundi"),
    Language(id: "ru", name: "Rusça", nameEn: "Russian"),
    Language(id: "sm", name: "Samo Dili (Latin)", nameEn: "Samo"),
    Language(id: "st", name: "Sesotho", nameEn: "Sesotho"),
    Language(id: "nso", name: "Sesotho sa Leboa", nameEn: "Sesotho sa Leboa"),
    Language(id: "tn", name: "Setswana", nameEn: "Tswana"),
    Language(id: "sd", name: "Sindhi", nameEn: "Sindhi"),
    Language(id: "si", name: "Sinhala Dili", nameEn: "Sinhalese"),
    Language(id: "sr-Cyrl", name: "Sırpça (Kiril)", nameEn: "Serbian Cyrillic"),
    Language(id: "sr-latn", name: "Sırpça (Latin)", nameEn: "Serbian Latin"),
    Language(id: "sk", name: "Slovakça", nameEn: "Slovak"),
    Language(id: "sl", name: "Slovence", nameEn: "Slovenian"),
    Language(id: "so", name: "Somalice", nameEn: "Somali"),
    Language(id: "sw", name: "Svahili Dili (Latin)", nameEn: "Swahili"),
    Language(id: "ty", name: "Tahiti Dili", nameEn: "Tahitian"),
    Language(id: "ta", name: "Tamilce", nameEn: "Tamil"),
    Language(id: "tt", name: "Tatar Dili (Latin)", nameEn: "Tatar"),
    Language(id: "th", name: "Tayca", nameEn: "Thai"),
    Language(id: "te", name: "Telugu Dili", nameEn: "Telugu"),
    Language(id: "bo", name: "Tibetçe", nameEn: "Lhasa Tibetan"),
    Language(id: "ti", name: "Tigrinya Dili", nameEn: "Tigrinya"),
    Language(id: "to", name: "Tonga Dili", nameEn: "Tongan"),
    Language(id: "tr", name: "Türkçe", nameEn: "Turkish"),
    Language(id: "tk", name: "Türkmen (Latin)", nameEn: "Turkmen"),
    Language(id: "uk", name: "Ukraynaca", nameEn: "Ukrainian"),
    Language(id: "ur", name: "Urduca", nameEn: "Urdu"),
    Language(id: "vi", name: "Vietnamca", nameEn: "Vietnamese"),
    Language(id: "yo", name: "Yoruba Dili", nameEn: "Yoruba"),
    Language(id: "hsb", name: "Yukarı Sorbça", nameEn: "Upper Sorbian"),
    Language(id: "yua", name: "Yukatek Mayacasi", nameEn: "Yucatec Maya"),
    Language(id: "el", name: "Yunanca", nameEn: "Greek"),
    Language(id: "xh", name: "Zosa Dili", nameEn: "Xhosa"),
    Language(id: "zu", name: "Zuluca", nameEn: "Zulu"),
    Language(id: "kn", name: "Kannada Dili", nameEn: "Kannada"),
    Language(id: "km", name: "Khmer Dili", nameEn: "Khmer"),
    Language(id: "tlh-Piqd", name: "klingonca (Latin)", nameEn: "Klingon"),
    Language(id: "ug", name: "Uygur Dili (Arapça)", nameEn: "Uyghur Arabic"),
    Language(id: "am", name: "Amharca", nameEn: "Amharic"),
    Language(id: "as", name: "Assamca", nameEn: "Assamca"),
    Language(id: "az", name: "Azerbaycan Dili", nameEn: "Azerbaijani"),
]
